### PR TITLE
Testing pipeline

### PR DESCRIPTION
**Pull request by colincoleman**

### CODE REVIEW

**Review by itsdalmo — COMMENTED** [review]
Awesome 💯 Will leave approval to Mikael since he is the original author 😅

**Review by mikael-lindstrom — APPROVED** [review]
LGTM 👍

**Comment by itsdalmo** [comment]
Should be a squash and merge I believe 🙌

**Comment by mikael-lindstrom** [comment]
Yes, please squash merge 👍

**Pull request merged**
